#! /usr/bin/env zsh

# Extract a compressed file
function extract() {
    local file="$1"

    if [[ ! -f ${file} ]]
    then
        echo "Not a file: ${file}"
        return 1
    fi

    case "${file}" in
        *.tar.bz2)  tar xjf "${file}";;
        *.tar.gz)   tar xzf "${file}";;
        *.tar)      tar xf "${file}";;

        *.bz2)      bunzip2 "${file}";;
        *.gz)       gunzip "${file}";;

        *.7z)       7z x "${file}";;
        *.rar)      7z x "${file}";;
        *.zip)      7z x "${file}";;

        *)          echo "Unknown file extension, could not be extracted"; return 2;;
    esac
}
